image: docker:latest

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

services:
- docker:dind

before_script:
  - apk add --no-cache curl bash
  - curl https://releases.hashicorp.com/packer/1.2.1/packer_1.2.1_linux_amd64.zip > packer_1.2.1_linux_amd64.zip && unzip packer_1.2.1_linux_amd64.zip && mv packer /usr/bin/packer
  - packer --version
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - build

build_docker:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - bash build-docker.sh
    - docker tag augury/wrf-standalone:latest $IMAGE_TAG
    - docker push $IMAGE_TAG

build_ebs:
  stage: build
  script:
    - find ./region -maxdepth 1 -name '*.json' -exec bash build.sh {} \;
  when: manual
  only:
    - master