image: docker:latest

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
  - curl https://releases.hashicorp.com/packer/1.2.1/packer_1.2.1_linux_amd64.zip & unzip packer_1.2.1_linux_amd64.zip & cp packer /usr/bin/packer
  - packer --version

stages:
  - deploy

build:
  stage: deploy
  script:
    - ./build-docker.sh
    - find ./region -maxdepth 1 -name '*.json' -exec ./build.sh {} \;
  when: manual
  only:
    - master