image: docker:latest

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind
- hashicorp/packer:1.0.4

before_script:
  - packer --version

stages:
  - deploy

build:
  stage: deploy
  script:
    - ./build-docker.sh
    - find ./region -maxdepth 1 -name '*.json' -exec ./build.sh {} \;
  when: manual
  only:
    - master