packer {
  required_plugins {
    docker = {
      source  = "github.com/hashicorp/docker"
      version = "~> 1"
    }
  }
}

variable "git_sha" {
  type    = string
  default = "none"
}

variable "name_prefix" {
  type    = string
  default = "wrf-standalone"
}

source "docker" "autogenerated_1" {
  commit  = true
  discard = false
  image   = "wrf-image-base:latest"
  pull    = false
}

build {
  sources = ["source.docker.autogenerated_1"]

  provisioner "shell" {
    scripts = ["scripts/install_deps.sh", "scripts/build_wrf.sh"]
  }

  post-processors {
    post-processor "docker-tag" {
      repository = "wrf/${var.name_prefix}"
      tag        = "${var.git_sha}"
    }
    post-processor "docker-tag" {
      repository = "wrf/${var.name_prefix}"
      tag        = "latest"
    }
  }
}
